### PR TITLE
1.2.21

### PR DESCRIPTION
**Pull request by flarco**
### GitHub Actions Workflows
- Updated `flarco/infisical-action` from v2 to v3 across multiple workflow files
- Modified version output handling in `build-dev.yml`
- Updated Go setup and caching configurations

### Configuration and Environment Variables
- Added support for `SLING_TASK_CONFIG` environment variable in `sling_run.go`

### Code Improvements
- Refactored replication and task configuration handling in `sling_run.go`
- Updated SQL query detection logic in `sling_conns.go`
- Modified error messages and documentation references

### Testing
- Added new test files and updated existing test configurations
- Expanded CLI test suite with new scenarios

### Documentation
- Updated `README.md` with new contributing guidelines and test instructions
- Added `.goreleaser.notes.md` with a link to the project repository

### Dependencies
- Updated various Go module dependencies to newer versions

### Build Scripts
- Modified MinIO client (mc) download URLs in CI preparation scripts

### CODE REVIEW

**Comment by yokofly** [comment]
seems some code broke the replication. I locally build with commit  [256b075](https://github.com/slingdata-io/sling-cli/pull/390/commits/256b0755ac83c6a162dc5f864d97f76db4d3dd3d)


```
 export DEBUG=LOW                                       
(base) ➜  sling-cli git:(1.2.21) ✗ ./sling run --src-conn LOCAL --src-stream file://cmd/sling/tests/files/test8.csv --src-options '{ delimiter: "|", quote: "$", escape: "\\" }'
fatal:
--- proc.go:271 main ---
--- sling_cli.go:458 main ---
--- sling_cli.go:494 cliInit ---
--- cli.go:286 CliProcess ---
--- sling_run.go:187 processRun ---
cannot get replication configuration.
(base) ➜  sling-cli git:(1.2.21) ✗ 
```

**Comment by flarco** [comment]
@yun, thanks, fixed with [2bc9e43](https://github.com/slingdata-io/sling-cli/pull/390/commits/2bc9e432941c7d367d103d96d638d37a0fc28b94)

**Comment by flarco** [comment]
@yokofly no pressure, do you think you'll get to open the other PR this week? Want to release 1.2.21 this weekend.
If not, we can include direct-write in next release.

**Comment by yokofly** [comment]
@flarco  I already have a pr, but I am worried about the rollback handle. let's discussed more in https://github.com/slingdata-io/sling-cli/pull/404

> @yokofly no pressure, do you think you'll get to open the other PR this week? Want to release 1.2.21 this weekend. If not, we can include direct-write in next release.

**Pull request merged**
