### PR TITLE
v1.0.68

### PR DESCRIPTION
**Pull request by flarco**
- Update BQ Truncate
- Fix MySQL bit parsing
- Use github.com/parquet-go/parquet-go for parquet
- add `stream_file_ext` object pattern
- Allow `*` file listing / expansion in replications
- Expand env_var for dbt connections
- Fix BigQuery Default Credentials

### CODE REVIEW

**Comment by johnoscott** [comment]
Can I request a change to {stream_file_folder} also before this PR is merged.

I tested the wildcard stream for a folder of CSV files as per #100 with this config:

```yaml
source: 'local://'
target: POSTGRES

defaults:
  mode: full-refresh
  object: '{stream_file_folder}.{stream_file_name}'
  source_options:
    format: csv

streams:
  "file://./csv/marketo/*.csv": # wildcard

```
The table names are now created as intended, but I want to use the parent folder name as the schema name - `marketo` in this case.

But i get this:

```
... snip :

9:14PM INF [3 / 3] running stream file://csv/marketo/contacts.csv
9:14PM INF connecting to target database (postgres)
9:14PM INF reading from source file system (file)
9:14PM INF writing to target database [mode: full-refresh]
9:14PM INF streaming data
9:14PM INF dropped table "csv_marketo_"."contacts"
9:14PM INF created table "csv_marketo_"."contacts"
9:14PM INF inserted 59 rows in 0 secs [558 r/s]
9:14PM INF execution succeeded
```

I would prefer that {stream_file_folder} resolve to the immediate parent folder, not the conformed path `csv_marketo_`.

**Comment by flarco** [comment]
Great, thanks for testing. Will do, I know what's happening.

**Comment by flarco** [comment]
@johnoscott  can you try now?

**Comment by johnoscott** [comment]
Its working as expected now - thankyou.

To summarise, I can now express what I think is an elegant solution to load many folders of csv files representing a schema per folder, and a table per csv file.

Just list a stream per folder using wildcard syntax for all csv files.

And have a default object configured for the schema name as the folder name, and the table name as the file name (without the file extension).

> file: csv_load_postgres.yaml
```yaml

source: 'local://'
target: POSTGRES

defaults:
  mode: full-refresh
  object: '{stream_file_folder}.{stream_file_name}'
  source_options:
    format: csv

streams:
  "file://./csv/marketo/*.csv":
  "file://./csv/salesforce/*.csv":
```

Run with : 
```
sling run --replication  ./csv_load_postgres.yaml
```

**Pull request merged**
